---
title: 'Class: R Function'
author: "Joan M Valls Cuevas"
date: "4/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Overview
Today we will focus on R functions. We will start with a bit of file reading

```{r}
x <- 1:10/2
plot(tan(x), type = "l", col = "blue")
```
Opening test1 using read.table() and modifying the conditions to fit the document
```{r}
read.table("test1.txt", sep = ",", header = TRUE)
```
A space and a tab does not need any special separators
```{r}
read.table("test3.txt")
```
A **$** sign was used as a separator in this example
```{r}
read.table("test2.txt", sep = "$", header = TRUE)
```

```{r}
read.csv("https://bioboot.github.io/bggn213_S19/class-material/test1.txt")
```

##Our first function

Add some numbers 

```{r}
add <- function(x=0, y=0) {
  #The body of the function
  return(x + y)
  
}
```

```{r}
add()
```

```{r}
add(c(1,3,5), 1)
```
Too many arguments
```{r}
#add(1,3,5)
```
```{r}
## You need a “name”, “arguments” and “body”...
rescale <- function(x) {
   rng <-range(x)
   (x - rng[1]) / (rng[2] - rng[1])
}

```


```{r}
# Test on a small example where you know the answer
rescale(1:10)
```

```{r}
## You need a “name”, “arguments” and “body”...
rescale2 <- function(x, na.rm = TRUE) {
   rng <-range(x, na.rm = na.rm)
   (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}

rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
   if(na.rm) {
     rng <-range(x, na.rm=TRUE)
   } else {
     rng <-range(x)
   }
   print("Hello")
   answer <- (x - rng[1]) / (rng[2] - rng[1])
   print("is it me you are looking for?")
   if(plot) {
      plot(answer, typ="b", lwd=4)
      print("Plot has been drawn")
}
   print("I can see it in ...")
   return(answer)
}
```



```{r}
doStuff <- function(x, typ="l", sse=sse, chain="A", ylab="Bfactor", elety="CA") { 

library("bio3d") #upload bio3d 
  
s1 <- read.pdb(x)  # kinase with drug

s1.chain <- trim.pdb(s1, chain=chain, elety=elety) 

s1.b <- s1.chain$atom$b

plotb3(s1.b, sse=s1.chainA, typ=typ, ylab=ylab)


}

```


```{r}
library("bio3d")
s1 <- read.pdb("4AKE")
s1
```
```{r}
s1.chain <- trim.pdb(s1, chain="A", elety="CA")
s1.chain
```
```{r}
s1.b <- s1.chain$atom$b
s1.b
```


